"""
Training Data Generator for Alloy SFT

This module implements the "Compiler-in-the-loop" training data generation:
1. Takes candidate Alloy code (generated by a model or hand-written)
2. Runs it through the Alloy oracle
3. Classifies the result and generates appropriate training examples
"""

from dataclasses import dataclass
from typing import List, Optional, Tuple

from alloy_oracle import AlloyOracle, OracleResponse, OracleStatus
from data_schema import (
    TrainingExample,
    TrainingDataset,
    TrainingTaskType,
    ToolCall,
    SeedExample
)


class TrainingDataGenerator:
    """
    Generates training data for LLM fine-tuning by classifying Alloy oracle results.
    
    This class implements the "Compiler-in-the-loop" training loop:
    1. Takes candidate Alloy code (generated by a model or hand-written)
    2. Runs it through the Alloy oracle
    3. Classifies the result and generates appropriate training examples
    """
    
    def __init__(self, oracle: Optional[AlloyOracle] = None, generation: int = 0):
        """
        Initialize the generator.
        
        Args:
            oracle: Alloy oracle instance. If None, creates a default one.
            generation: Current generation number for examples.
        """
        self.oracle = oracle or AlloyOracle()
        self.generation = generation
        self.dataset = TrainingDataset(generation=generation)
    
    def set_generation(self, generation: int) -> None:
        """Set the current generation number."""
        self.generation = generation
        self.dataset.generation = generation
    
    def process_candidate(
        self,
        instruction: str,
        candidate_code: str,
        command_name: Optional[str] = None
    ) -> Tuple[OracleResponse, Optional[TrainingExample]]:
        """
        Process a candidate Alloy module and generate training examples.
        
        Args:
            instruction: The natural language instruction that prompted this code.
            candidate_code: The Alloy code to evaluate.
            command_name: Optional command to run.
            
        Returns:
            Tuple of (oracle response, generated training example or None)
        """
        response = self.oracle.run(candidate_code, command_name)
        example = self._classify_and_generate(instruction, candidate_code, response)
        
        if example:
            self.dataset.add(example)
        
        return response, example
    
    def add_positive_example(
        self,
        instruction: str,
        alloy_code: str,
        task_type: TrainingTaskType = TrainingTaskType.NL_TO_ALLOY,
        validate: bool = True
    ) -> TrainingExample:
        """
        Create a positive training example from a successful run.
        Used for hand-curated examples or verified model outputs.
        
        Args:
            instruction: The natural language instruction.
            alloy_code: The correct Alloy code.
            task_type: The type of task this represents.
            validate: Whether to validate with the oracle.
            
        Returns:
            The created example.
        """
        example = TrainingExample(
            task_type=task_type,
            instruction=instruction,
            target_output=alloy_code,
            is_positive=True,
            generation=self.generation
        )
        
        if validate:
            response = self.oracle.parse_only(alloy_code)
            if response.has_compile_errors():
                example.is_positive = False
                example.metadata["validation_errors"] = str(response.errors)
        
        self.dataset.add(example)
        return example
    
    def add_fix_example(
        self,
        original_code: str,
        corrected_code: str,
        compiler_error: Optional[str] = None
    ) -> TrainingExample:
        """
        Create a "fix error" training example from broken code.
        
        Args:
            original_code: The broken Alloy code.
            corrected_code: The fixed Alloy code.
            compiler_error: Optional explicit error message.
            
        Returns:
            The created example.
        """
        # Determine error type from original code
        original_response = self.oracle.parse_only(original_code)
        
        if original_response.status == OracleStatus.PARSE_ERROR:
            task_type = TrainingTaskType.FIX_PARSE_ERROR
            instruction = "Fix the following Alloy code that has syntax errors."
        elif original_response.status == OracleStatus.TYPE_ERROR:
            task_type = TrainingTaskType.FIX_TYPE_ERROR
            instruction = "Fix the following Alloy code that has type errors."
        else:
            task_type = TrainingTaskType.FIX_PARSE_ERROR
            instruction = "Fix the following Alloy code that has errors."
        
        # Format the compiler feedback
        if compiler_error:
            feedback = compiler_error
        else:
            feedback = self._format_errors(original_response)
        
        example = TrainingExample(
            task_type=task_type,
            instruction=instruction,
            alloy_context=original_code,
            compiler_feedback=feedback,
            target_output=corrected_code,
            is_positive=True,
            generation=self.generation
        )
        
        # Validate the corrected code
        corrected_response = self.oracle.parse_only(corrected_code)
        if corrected_response.has_compile_errors():
            example.is_positive = False
            example.metadata["validation_errors"] = str(corrected_response.errors)
        
        self.dataset.add(example)
        return example
    
    def add_assertion_example(
        self,
        module_code: str,
        assertion_code: str,
        description: str
    ) -> TrainingExample:
        """
        Create an assertion generation training example.
        
        Args:
            module_code: The Alloy module.
            assertion_code: The assertion and check command to add.
            description: Natural language description of the property.
            
        Returns:
            The created example.
        """
        example = TrainingExample(
            task_type=TrainingTaskType.GENERATE_ASSERTION,
            instruction=description,
            alloy_context=module_code,
            target_output=assertion_code,
            is_positive=True,
            generation=self.generation
        )
        
        self.dataset.add(example)
        return example
    
    def add_tool_call_example(
        self,
        user_goal: str,
        context: str,
        tool_name: str,
        tool_args: dict,
        response_text: str = ""
    ) -> TrainingExample:
        """
        Create a tool-call training example.
        
        Args:
            user_goal: What the user wants to accomplish.
            context: Context for the task.
            tool_name: The tool to call.
            tool_args: Arguments for the tool.
            response_text: Optional text response.
            
        Returns:
            The created example.
        """
        tool_call = ToolCall(tool=tool_name, args=tool_args)
        
        example = TrainingExample(
            task_type=TrainingTaskType.TOOL_CALL,
            instruction=user_goal,
            alloy_context=context,
            target_output=response_text,
            tool_call=tool_call,
            is_positive=True,
            generation=self.generation
        )
        
        self.dataset.add(example)
        return example
    
    def add_seed_examples(self, seed_examples: List[SeedExample]) -> int:
        """
        Add a batch of seed examples.
        
        Args:
            seed_examples: List of seed examples to add.
            
        Returns:
            Number of examples added.
        """
        count = 0
        for seed in seed_examples:
            for example in seed.to_training_examples():
                self.dataset.add(example)
                count += 1
        return count
    
    def get_dataset(self) -> TrainingDataset:
        """Get the current dataset."""
        return self.dataset
    
    def get_positive_examples(self) -> List[TrainingExample]:
        """Get only positive examples suitable for SFT."""
        return self.dataset.get_positive_examples()
    
    def get_examples_needing_correction(self) -> List[TrainingExample]:
        """Get examples that need human correction (failures)."""
        return self.dataset.get_examples_needing_correction()
    
    def export_jsonl(self, output_path: str, include_negative: bool = False) -> None:
        """
        Export examples to JSONL format for vendor fine-tuning.
        
        Args:
            output_path: Path to the output file.
            include_negative: Whether to include negative examples.
        """
        self.dataset.save_jsonl(output_path, include_negative)
    
    def export_openai_format(self, output_path: str) -> None:
        """
        Export examples in OpenAI fine-tuning format.
        
        Args:
            output_path: Path to the output file.
        """
        self.dataset.save_openai_format(output_path)
    
    def clear(self) -> None:
        """Clear all collected examples."""
        self.dataset.clear()
    
    def _classify_and_generate(
        self,
        instruction: str,
        candidate_code: str,
        response: OracleResponse
    ) -> Optional[TrainingExample]:
        """Classify the oracle response and generate appropriate training example."""
        
        if response.status == OracleStatus.PARSE_ERROR:
            # Create a "fix parse error" task
            return TrainingExample(
                task_type=TrainingTaskType.FIX_PARSE_ERROR,
                instruction="Fix the following Alloy code that has syntax errors.",
                alloy_context=candidate_code,
                compiler_feedback=self._format_errors(response),
                is_positive=False,  # Needs human correction for the output
                generation=self.generation
            )
        
        elif response.status == OracleStatus.TYPE_ERROR:
            # Create a "fix type error" task
            return TrainingExample(
                task_type=TrainingTaskType.FIX_TYPE_ERROR,
                instruction="Fix the following Alloy code that has type errors.",
                alloy_context=candidate_code,
                compiler_feedback=self._format_errors(response),
                is_positive=False,  # Needs human correction for the output
                generation=self.generation
            )
        
        elif response.status in (OracleStatus.INSTANCE_FOUND, OracleStatus.NO_INSTANCE):
            # Successful execution - this is a positive example
            return TrainingExample(
                task_type=TrainingTaskType.NL_TO_ALLOY,
                instruction=instruction,
                target_output=candidate_code,
                is_positive=True,
                generation=self.generation
            )
        
        elif response.status == OracleStatus.TIMEOUT:
            # Could be used for "avoid infinite search" training
            return TrainingExample(
                task_type=TrainingTaskType.NL_TO_ALLOY,
                instruction=instruction,
                alloy_context=candidate_code,
                compiler_feedback="Solver timed out - the model may be too complex or have an infinite search space.",
                is_positive=False,
                generation=self.generation
            )
        
        else:
            # Other errors - mark as needing attention
            return TrainingExample(
                task_type=TrainingTaskType.NL_TO_ALLOY,
                instruction=instruction,
                alloy_context=candidate_code,
                compiler_feedback=self._format_errors(response),
                is_positive=False,
                generation=self.generation
            )
    
    def _format_errors(self, response: OracleResponse) -> str:
        """Format errors from an oracle response."""
        if not response.errors:
            return response.summary or ""
        
        error_strings = [str(err) for err in response.errors]
        return "\n".join(error_strings)
