pluginManagement {
  plugins {
    id 'biz.aQute.bnd.workspace' version bnd_version
    id 'info.solidsoft.pitest' version '1.15.0'
  }
  repositories {
    maven {
      url = uri(bnd_snapshots)
      content {
        snapshotsOnly()
        includeGroup('biz.aQute.bnd')
        includeGroup('biz.aQute.bnd.workspace')
      }
    }
    mavenCentral()
    gradlePluginPortal()
  }
}
plugins {
  id 'biz.aQute.bnd.workspace'
}
