package org.alloytools.alloy.training;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Generates training data for LLM fine-tuning by classifying Alloy oracle results.
 * 
 * This class implements the "Compiler-in-the-loop" training loop:
 * 1. Takes candidate Alloy code (generated by a model or hand-written)
 * 2. Runs it through the Alloy oracle
 * 3. Classifies the result and generates appropriate training examples
 */
public class TrainingDataGenerator {
    
    private final AlloyOracle oracle;
    private final List<TrainingExample> examples;
    private int generation;
    
    /**
     * Create a generator with default oracle settings.
     */
    public TrainingDataGenerator() {
        this(new AlloyOracle());
    }
    
    /**
     * Create a generator with a custom oracle.
     */
    public TrainingDataGenerator(AlloyOracle oracle) {
        this.oracle = oracle;
        this.examples = new ArrayList<>();
        this.generation = 0;
    }
    
    /**
     * Set the current generation number for training examples.
     */
    public void setGeneration(int generation) {
        this.generation = generation;
    }
    
    /**
     * Process a candidate Alloy module and generate training examples.
     * 
     * @param instruction the natural language instruction that prompted this code
     * @param candidateCode the Alloy code to evaluate
     * @return the oracle response from evaluating the code
     */
    public OracleResponse processCandidate(String instruction, String candidateCode) {
        return processCandidate(instruction, candidateCode, null);
    }
    
    /**
     * Process a candidate Alloy module with a specific command.
     * 
     * @param instruction the natural language instruction
     * @param candidateCode the Alloy code to evaluate
     * @param commandName the command to run (null for default)
     * @return the oracle response
     */
    public OracleResponse processCandidate(String instruction, String candidateCode, String commandName) {
        OracleResponse response = oracle.run(candidateCode, commandName);
        
        TrainingExample example = classifyAndGenerate(instruction, candidateCode, response);
        if (example != null) {
            examples.add(example);
        }
        
        return response;
    }
    
    /**
     * Create a positive training example from a successful run.
     * Used for hand-curated examples or verified model outputs.
     * 
     * @param instruction the natural language instruction
     * @param alloyCode the correct Alloy code
     * @param taskType the type of task this represents
     * @return the created example
     */
    public TrainingExample addPositiveExample(String instruction, String alloyCode, TrainingTaskType taskType) {
        TrainingExample example = new TrainingExample(taskType, instruction, alloyCode);
        example.id = generateId();
        example.generation = this.generation;
        example.isPositive = true;
        
        // Optionally validate with oracle
        OracleResponse response = oracle.parseOnly(alloyCode);
        if (!response.hasCompileErrors()) {
            example.oracleResponse = response;
        }
        
        examples.add(example);
        return example;
    }
    
    /**
     * Create a "fix error" training example from broken code.
     * 
     * @param originalCode the broken Alloy code
     * @param correctedCode the fixed Alloy code
     * @param compilerError the error message from the original
     * @return the created example
     */
    public TrainingExample addFixExample(String originalCode, String correctedCode, String compilerError) {
        OracleResponse originalResponse = oracle.parseOnly(originalCode);
        
        TrainingTaskType taskType;
        if (originalResponse.status == OracleStatus.PARSE_ERROR) {
            taskType = TrainingTaskType.FIX_PARSE_ERROR;
        } else if (originalResponse.status == OracleStatus.TYPE_ERROR) {
            taskType = TrainingTaskType.FIX_TYPE_ERROR;
        } else {
            taskType = TrainingTaskType.FIX_PARSE_ERROR; // Default
        }
        
        TrainingExample example = new TrainingExample();
        example.id = generateId();
        example.taskType = taskType;
        example.instruction = "Fix the following Alloy code that has compilation errors.";
        example.alloyContext = originalCode;
        example.compilerFeedback = compilerError != null ? compilerError : formatErrors(originalResponse);
        example.targetOutput = correctedCode;
        example.generation = this.generation;
        example.isPositive = true;
        
        // Validate the corrected code
        OracleResponse correctedResponse = oracle.parseOnly(correctedCode);
        if (!correctedResponse.hasCompileErrors()) {
            example.oracleResponse = correctedResponse;
        }
        
        examples.add(example);
        return example;
    }
    
    /**
     * Create an assertion generation training example.
     * 
     * @param moduleCode the Alloy module
     * @param assertionCode the assertion and check command to add
     * @param description natural language description of the property
     * @return the created example
     */
    public TrainingExample addAssertionExample(String moduleCode, String assertionCode, String description) {
        TrainingExample example = new TrainingExample();
        example.id = generateId();
        example.taskType = TrainingTaskType.GENERATE_ASSERTION;
        example.instruction = description;
        example.alloyContext = moduleCode;
        example.targetOutput = assertionCode;
        example.generation = this.generation;
        example.isPositive = true;
        
        examples.add(example);
        return example;
    }
    
    /**
     * Get all collected training examples.
     */
    public List<TrainingExample> getExamples() {
        return new ArrayList<>(examples);
    }
    
    /**
     * Get only positive examples suitable for SFT.
     */
    public List<TrainingExample> getPositiveExamples() {
        List<TrainingExample> positive = new ArrayList<>();
        for (TrainingExample ex : examples) {
            if (ex.isPositive) {
                positive.add(ex);
            }
        }
        return positive;
    }
    
    /**
     * Get examples that need human correction (failures).
     */
    public List<TrainingExample> getExamplesNeedingCorrection() {
        List<TrainingExample> needsWork = new ArrayList<>();
        for (TrainingExample ex : examples) {
            if (!ex.isPositive && ex.oracleResponse != null && ex.oracleResponse.hasCompileErrors()) {
                needsWork.add(ex);
            }
        }
        return needsWork;
    }
    
    /**
     * Export examples to JSONL format for vendor fine-tuning.
     * 
     * @param outputFile the output file path
     * @throws IOException if writing fails
     */
    public void exportToJsonl(File outputFile) throws IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(outputFile))) {
            for (TrainingExample example : getPositiveExamples()) {
                writer.write(toJsonlLine(example));
                writer.newLine();
            }
        }
    }
    
    /**
     * Export examples in simple input/output format.
     * 
     * @param outputFile the output file path
     * @throws IOException if writing fails
     */
    public void exportSimpleFormat(File outputFile) throws IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(outputFile))) {
            for (TrainingExample example : getPositiveExamples()) {
                writer.write(toSimpleJsonlLine(example));
                writer.newLine();
            }
        }
    }
    
    /**
     * Clear all collected examples.
     */
    public void clear() {
        examples.clear();
    }
    
    /**
     * Shutdown the generator and its oracle.
     */
    public void shutdown() {
        oracle.shutdown();
    }
    
    // ---- Internal methods ----
    
    private TrainingExample classifyAndGenerate(String instruction, String candidateCode, OracleResponse response) {
        TrainingExample example = new TrainingExample();
        example.id = generateId();
        example.generation = this.generation;
        example.oracleResponse = response;
        
        switch (response.status) {
            case PARSE_ERROR:
                // Create a "fix parse error" task
                example.taskType = TrainingTaskType.FIX_PARSE_ERROR;
                example.instruction = "Fix the following Alloy code that has syntax errors.";
                example.alloyContext = candidateCode;
                example.compilerFeedback = formatErrors(response);
                example.isPositive = false; // Needs human correction for the output
                return example;
                
            case TYPE_ERROR:
                // Create a "fix type error" task
                example.taskType = TrainingTaskType.FIX_TYPE_ERROR;
                example.instruction = "Fix the following Alloy code that has type errors.";
                example.alloyContext = candidateCode;
                example.compilerFeedback = formatErrors(response);
                example.isPositive = false; // Needs human correction for the output
                return example;
                
            case INSTANCE_FOUND:
            case NO_INSTANCE:
                // Successful execution - this is a positive example
                example.taskType = TrainingTaskType.NL_TO_ALLOY;
                example.instruction = instruction;
                example.targetOutput = candidateCode;
                example.isPositive = true;
                return example;
                
            case TIMEOUT:
                // Could be used for "avoid infinite search" training
                example.taskType = TrainingTaskType.NL_TO_ALLOY;
                example.instruction = instruction;
                example.alloyContext = candidateCode;
                example.compilerFeedback = "Solver timed out - the model may be too complex or have an infinite search space.";
                example.isPositive = false;
                return example;
                
            case ERROR:
            default:
                // Other errors - mark as needing attention
                example.taskType = TrainingTaskType.NL_TO_ALLOY;
                example.instruction = instruction;
                example.alloyContext = candidateCode;
                example.compilerFeedback = formatErrors(response);
                example.isPositive = false;
                return example;
        }
    }
    
    private String formatErrors(OracleResponse response) {
        if (response.errors.isEmpty()) {
            return response.summary != null ? response.summary : "";
        }
        
        StringBuilder sb = new StringBuilder();
        for (OracleError error : response.errors) {
            sb.append(error.toString()).append("\n");
        }
        return sb.toString().trim();
    }
    
    private String generateId() {
        return "train-" + UUID.randomUUID().toString().substring(0, 8);
    }
    
    private String toJsonlLine(TrainingExample example) {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        sb.append("\"id\":\"").append(escapeJson(example.id)).append("\",");
        sb.append("\"task_type\":\"").append(example.taskType.getId()).append("\",");
        sb.append("\"generation\":").append(example.generation).append(",");
        sb.append("\"input\":").append(jsonString(example.formatInput())).append(",");
        sb.append("\"output\":").append(jsonString(example.targetOutput));
        
        if (example.toolCall != null) {
            sb.append(",\"tool_call\":{");
            sb.append("\"tool\":\"").append(escapeJson(example.toolCall.tool)).append("\"");
            sb.append("}");
        }
        
        sb.append("}");
        return sb.toString();
    }
    
    private String toSimpleJsonlLine(TrainingExample example) {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        sb.append("\"input\":").append(jsonString(example.formatInput())).append(",");
        sb.append("\"output\":").append(jsonString(example.targetOutput));
        sb.append("}");
        return sb.toString();
    }
    
    private String jsonString(String value) {
        if (value == null) {
            return "null";
        }
        return "\"" + escapeJson(value) + "\"";
    }
    
    private String escapeJson(String value) {
        if (value == null) {
            return "";
        }
        return value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t");
    }
}
